name: Build for iOS

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build IPA
        run: |
          chmod +x gradlew
          ./gradlew ios:createIPA
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Brick Breaker IPA
          path: ios/build/robovm/
          retention-days: 5
